---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: jet-githubprov-config
  labels:
    app: crossplane-githubprov
spec:
  image: crossplane/githubprov-controller:v0.1.0
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-githubprov
spec:
  package: crossplane/githubprov:v0.1.0
  controllerConfigRef:
    name: jet-githubprov-config
